### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MattFoley** [pbaumstarck/iOS-Chess#1]
Would you mind adding a license to this repository, MIT would be great? I'd like to use it to test out some things I've been working on, but I wanted to make sure I had permission! Thanks!

**Comment by pbaumstarck** [comment]
Sure, just added one (MIT). I hope you find it useful! I tested the code before I uploaded it to make sure it was still working (and to make the screenshot), but my Mac is a little old now: XCode 4.2 running on OS 10.6.8. So I don't know if there will be issues if you upgrade it to newer versions.
